<a href="https://colab.research.google.com/github/gachet/000mis-colabs/blob/master/Ejercicios_numpy_SOLUCIONES.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

### Crear un vector con valores dentro del rango 10 a 49

In [0]:
a = np.arange(10,50)
a

### Invertir el vector

In [0]:
a[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

### Crear una matriz 3x3 con valores de 0 a 8

In [0]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### Encontrar los indices que no son ceros del arreglo [1,2,4,2,4,0,1,0,0,0,12,4,5,6,7,0]

In [0]:
a = np.array([1,2,4,2,4,0,1,0,0,0,12,4,5,6,7,0])
np.argwhere( a!=0 )

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 6],
       [10],
       [11],
       [12],
       [13],
       [14]])

### Crear una matriz identidad de 6x6

In [0]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

### Crear una matriz con valores al azar con forma 3x3x3 

In [0]:
r = np.random.random((3,3,3))
r

array([[[0.41061073, 0.78966396, 0.1497036 ],
        [0.65097477, 0.67702346, 0.40101324],
        [0.58060751, 0.36709058, 0.36542752]],

       [[0.42380789, 0.76388923, 0.03371246],
        [0.19704932, 0.22645818, 0.46507731],
        [0.78391412, 0.47828961, 0.15350741]],

       [[0.01920386, 0.94412374, 0.19849807],
        [0.94878298, 0.5765844 , 0.62137004],
        [0.67720483, 0.73145512, 0.16483656]]])

### Encontrar los indices de los valores minimos y maximos de la anterior matriz

In [0]:
print( r.argmax() )
print( r.ravel()[r.argmax()] )

print(r)
print(np.unravel_index(r.argmax(), r.shape))
r[np.unravel_index(r.argmax(), r.shape)]

21
0.9487829795946848
[[[0.41061073 0.78966396 0.1497036 ]
  [0.65097477 0.67702346 0.40101324]
  [0.58060751 0.36709058 0.36542752]]

 [[0.42380789 0.76388923 0.03371246]
  [0.19704932 0.22645818 0.46507731]
  [0.78391412 0.47828961 0.15350741]]

 [[0.01920386 0.94412374 0.19849807]
  [0.94878298 0.5765844  0.62137004]
  [0.67720483 0.73145512 0.16483656]]]
(2, 1, 0)


0.9487829795946848

### Crear una matriz de 10x10 con 1's en los bordes y 0 en el interior (con rangos de indices)

In [0]:
z = np.ones((10,10))

z[1:-1,1:-1] = 0
z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

### Crear una matriz de 5x5 con valores en los renglones que vayan de 0 a 4

In [0]:
np.tile( np.arange(0,5) , 5).reshape(5,5)

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

### Crear dos arreglos al azar A y B, verificar si son iguales

In [0]:
a = np.random.random((3,3))
b = np.random.random((3,3))

a == b 

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [0]:
np.allclose(a,b)  # Con tolerancia, dada por argumentos: rtol atol


In [0]:
np.array_equal(a,b)