<a href="https://colab.research.google.com/github/gachet/mis-colabs/blob/master/Intro_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


<h2 id="NumPy">NumPy<a class="anchor-link" href="#NumPy">¶</a></h2>


In [0]:
import numpy as np


<p>El objeto principal de NumPy es el array  multidimensional homogéneo. Es una tabla de elementos (habitualmente números), todos del mismo tipo, indexados por una tupla de enteros positivos. En NumPy las dimensiones se llaman ejes. El número de ejes es el rango.</p>
<p>Hay muchas formas de crear un array NumPy. Por ejemplo,</p>


In [0]:

a = np.array([1, 2, 3, 4])
b = np.array([(1.5, 2, 3), (4, 5, 6)])
c = np.zeros((3, 4))
d = np.arange(1, 10, 2)          
print("EL vector a es ", a)
print("La matriz b es \n",b)
print("La matriz c es \n", c)
print("EL vector d es ", d)


EL vector a es  [1 2 3 4]
La matriz b es 
 [[1.5 2.  3. ]
 [4.  5.  6. ]]
La matriz c es 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
EL vector d es  [1 3 5 7 9]


In [0]:
numeros = np.arange(10.)               # Array de numeros (floats) de 0 a 9
print(numeros)
lista_ceros = np.zeros(10)             # Array de 10 ceros (floats)
print(lista_ceros)
lista_unos = np.ones(10)                # Array de 10 unos (floats)
print(lista_unos)
otra_lista = np.linspace(0, 30, 8)       # Array de 8 números, de 0 a 30 ambos incluidos
print(otra_lista)


[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[ 0.          4.28571429  8.57142857 12.85714286 17.14285714 21.42857143
 25.71428571 30.        ]



<h3 id="Indexado">Indexado<a class="anchor-link" href="#Indexado">¶</a></h3><p>Es parecido al utilizado en las listas. </p>



<p>Los índices comienzan en cero. El índice <code>-1</code> da el último elemento del array.</p>
<p>En <code>arange</code>, los valores se generan en el intervalo [1,10). Es decir, 1 está incluído pero 10 no lo está. El último índice es el paso. Es similar a <code>range</code> pero mientras este genera una lista, <code>arange</code> genera un array numpy.</p>


In [0]:
a[0]    =  1 
b[0,0]  =  2.5 
b[0][1] =  3.5
d[-1]   =  9
b

array([[2.5, 3.5, 3. ],
       [4. , 5. , 6. ]])

In [0]:
print(numeros[3:8])           # Elementos desde el tercero al septimo
print(numeros[:4])            # Elementos desde el primero al cuarto
print(numeros[5:])            # Elementos desde el quinto al final
print(numeros[-3])            # El antepenúltimo elemento (devuelve un elemento, no un array)
print(numeros[:])             # Todo el array, equivalente a print(numeros)
print(numeros[2:8:2])         # Elementos del segundo al septimo, pero saltando de dos en dos


[3. 4. 5. 6. 7.]
[0. 1. 2. 3.]
[5. 6. 7. 8. 9.]
7.0
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[2. 4. 6.]


Si creamos un array con np.arange() usando un número entero, el array que se creará será de enteros. Es posible cambiar todo el array a otro tipo de dato (como a float) usando el método astype():

In [0]:
enteros = np.arange(6)
print(enteros)
type(enteros)
type(enteros[0])
decimales = enteros.astype('float')
type(decimales)
type(decimales[0])
print(decimales)
print(decimales.shape)   # Forma o tamaño del array


[0 1 2 3 4 5]
[0. 1. 2. 3. 4. 5.]
(6,)


In [0]:

a = np.arange(10)
b = np.array([0, 1, 5, -1])

a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
a[1:8]

array([1, 2, 3, 4, 5, 6, 7])

In [0]:
a[1:8:2]

array([1, 3, 5, 7])

In [0]:
print (a[-1])
print (a[:-1])
print(a[3])
print(a[3:])
print(a[b])


9
[0 1 2 3 4 5 6 7 8]
3
[3 4 5 6 7 8 9]
[0 1 5 9]



<p>Análogamente para arrays multidimensionales:</p>


In [0]:

a = np.array([[1, 2, 4], [3, -1, 2]])
print ("a es",a)
print("a[0,2] es ",a[0,2])
print("a[:,1] es ",a[:,1])
print("a[0,:]es ",a[0,] )

##x[start:stop:step]

##If any of these are unspecified, 
##they default to the values start=0, 
##stop=size of dimension, step=1. 
##We'll take a look at accessing sub-arrays 
##in one dimension and in multiple dimensions.

print("a[:1, :2] es ",a[:1, :2] ) ## 1 FILA 2 COLUMNAS

a es [[ 1  2  4]
 [ 3 -1  2]]
a[0,2] es  4
a[:,1] es  [ 2 -1]
a[0,:]es  [1 2 4]
a[:1, :2] es  [[1 2]]



<h3 id="Operaciones-básicas-con-arrays-numpy">Operaciones básicas con arrays numpy<a class="anchor-link" href="#Operaciones-b%C3%A1sicas-con-arrays-numpy">¶</a></h3><p>Los operadores aritméticos se aplican en los arrays elemento a elemento. ¡Las listas Python funcionan de forma diferente!</p>
<ul>
<li>len: número de elementos de un array de dimensión uno (vector) of número de filas en un array de dimensión dos (matriz).
<li>ndim: número de dimensiones del array (1 para vector, 2 para matriz).
<li>shape: número de elementos en cada dimensión (número de filas y columnas para una matriz).
</ul>


In [0]:
##RECORDAD QUE ESTAS SON LISTAS
a1 = [1, 2, 3, 4]
b1 = [1.5, 2, 3, 5]


a = np.array([1, 2, 3, 4])
b = np.array([1.5, 6, 7,8])


print("longitud sw a", len(a))
print("longitud de la primera dimensión de b", len(b))
print("dimensión de a", a.ndim)
print("dimensión de b", b.ndim)
print("número de elementos de cada dimensióndimensión de a", b.shape)
print
print("vectores a y b ",a,b)
print("vector a+b " ,a+b)
print ("lista",a1+b1)
print ("vector 3+a",3+a) 
print("vector 3*",3*a)
print("vector 3/a ",3/a)
print("vector a/2",a/2)

longitud sw a 4
longitud de la primera dimensión de b 4
dimensión de a 1
dimensión de b 1
número de elementos de cada dimensióndimensión de a (4,)
vectores a y b  [1 2 3 4] [1.5 6.  7.  8. ]
vector a+b  [ 2.5  8.  10.  12. ]
lista [1, 2, 3, 4, 1.5, 2, 3, 5]
vector 3+a [4 5 6 7]
vector 3* [ 3  6  9 12]
vector 3/a  [3.   1.5  1.   0.75]
vector a/2 [0.5 1.  1.5 2. ]


Los arrays permiten hacer operaciones aritméticas básicas entre ellos en la forma que uno esperaría que se hicieran, es decir, haciéndolo elemento a elemento; para ello siempre ambos arrays deben tener la misma longitud, por ejemplo:

In [0]:
x = np.array([5.6, 7.3, 7.7, 2.3, 4.2, 9.2])

print ("Vector X es \n", x)
print ("Vector decimales es \n", decimales)


print("SUMA \n",x+decimales)

print("MULTIPLICACION \n", x*decimales)

print("DIVISION\n",x/decimales)


Vector X es 
 [5.6 7.3 7.7 2.3 4.2 9.2]
Vector decimales es 
 [0. 1. 2. 3. 4. 5.]
SUMA 
 [ 5.6  8.3  9.7  5.3  8.2 14.2]
MULTIPLICACION 
 [ 0.   7.3 15.4  6.9 16.8 46. ]
DIVISION
 [       inf 7.3        3.85       0.76666667 1.05       1.84      ]


C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: RuntimeWarning: divide by zero encountered in true_divide
  # This is added back by InteractiveShellApp.init_path()



<p>En el caso de matrices, a  diferencia de otros lenguajes, el operador <code>*</code> se aplica elemento a elemento en los arrays NumPy.</p>


In [0]:

A = np.array( [[1, 1], [0, 1]] )
B = np.array( [[2, 3], [1, 4]] )
C = A*B
C


array([[2, 3],
       [0, 4]])

In [0]:
z = np.array([5.6, 7.3, 7.7, 2.3, 4.2, 9.2])
print("maximo",z.max())   # Valor máximo de los elementos del array
print("minimo",z.min())   # Valor mínimo de los elementos del array
print("Media",z.mean())  # Valor medio de los elementos del array
print("Desviación Típica",z.std())   # Desviación típica de los elementos del array
print("Sumatoria",z.sum())   # Suma de todos los elementos del array
print("Mediana",np.median(z)) # Mediana de los elementos del array


maximo 9.2
minimo 2.3
Media 6.05
Desviación Típica 2.305609102457165
Sumatoria 36.3
Mediana 6.449999999999999


Otras Operaciones

In [0]:

print(np.sin(np.pi/2))
print(np.exp(-1))
print(np.arctan(np.inf))
print(np.sqrt(4))



1.0
0.36787944117144233
1.5707963267948966
2.0



<h3 id="Copias">Copias<a class="anchor-link" href="#Copias">¶</a></h3><p>Cuando operamos y manipulamos arrays, algunas veces, sus datos se copian en un nuevo array, mientras que otras no. Esto crea confusión. Veamos ALGUNOS ejemplos:</p>
<p><strong>Sin copia</strong>: Con una asignación sencilla modificamos de los arrays (no hay copia).</p>


In [0]:

a = np.arange(12)
b = a
b


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [0]:
b[0] = 10
print("b es ", b)
print("a es ",a)

b es  [10  1  2  3  4  5  6  7  8  9 10 11]
a es  [10  1  2  3  4  5  6  7  8  9 10 11]



<p><strong>Con copia</strong>: el método <code>copy</code> realiza una copia completa del array y de sus datos en otro segmento de memoria.</p>


In [0]:

## Create an array x, with a reference y and a copy z:

x = np.array([1, 2, 3])
y = x
z = np.copy(x)

## Cuando modificamos x, y cambia ,  z:


In [0]:
## Cuando modificamos x, y cambia , pero no z:

x[0] = 10
x[0] == y[0]


True

In [0]:
x[0] == z[0]

False



En el primer caso, el símbolo '=' crea un objeto b que apunta al mismo segmento de memoria. A esto lo podemos llamar 'vista' o 'referencia', ya que sólo se diferencia de a en el nombre.

En el segundo caso, a.copy() está generando una copia real física: un duplicado del segmento de memoria de a en otra región del espacio memoria y por lo tanto con otra dirección. Al hacer b = a.copy(), le estamos asignando al nombre de variable b, ese nuevo espacio de memoria. Esto se llama 'copia'.


### Rendimiento: cálculo de la norma de un vector 

La norma de un vector  $x$ es: 

$$
\| x \| = \sqrt{\sum_{i=0}^{n-1} x_{i} x_{i}}
$$

donde $x_{i}$ es el  $i$th elemento de  $x$. Es rl producto punto de un vector consigo mismo, 
seguido de su raíz cuadrada.
Para calcular la norma  podemos iterar a través de elos elementos del vector, calcular el cuadrado de cada elemento y finalmente obtener la raíz cuadrada.

Calcularemos la norma de un vector de º0 millones de elementos utilizando dos métodos para comparar el rendimiento de caa uno midiendo el tiempo de CPU utilizado.


In [0]:
# NumPy array con 10 millones de valores aleatorios
x = np.random.rand(10000000)
print(type(x))

<class 'numpy.ndarray'>


Medimos el tiempo utilizando la función NumPy  '`numpy.dot`'. Utlizamos el  'comando mágico de jupyter' [`%time`](Notebook%20tips.ipynb#Simple-timing): 

In [0]:
%time norm = np.sqrt(np.dot(x, x))
print("la norma es",norm)

Wall time: 130 ms
la norma es 1825.7676365173174


Nos interesa '`Wall time`'.

Hacemos el mismo cálculo pero con nuestra propia función para iterar sobre los elementos del vector y calcular la norma:

In [0]:
def compute_norm(x):
    norm = 0.0
    for xi in x:
        norm += xi*xi
    return np.sqrt(norm)

%time norm =compute_norm(x)
print("la norma es",norm)

Wall time: 4.19 s
la norma es 1825.7676365174702


El resultado es el mismo pero la función NumPy function es como 100 (depende del ordenador) veces más rápida!

### Más sobre matrices



#### Multiplicación Matriz-vector y matriz-matriz

COnsideramos la matriz $A$:

$$
A  = 
\begin{bmatrix}
3.4 & 2.6 \\
2.1 & 4.5
\end{bmatrix}
$$

y el vector $x$:

$$
x  = 
\begin{bmatrix}
0.2 \\ -1.1
\end{bmatrix}
$$

In [0]:
A = np.array([[3.4, 2.6], [2.1, 4.5]])
print("Matriz A:\n {}".format(A))

x = np.array([0.2, -1.1])
print("Vector x:\n {}".format(x))

Matriz A:
 [[3.4 2.6]
 [2.1 4.5]]
Vector x:
 [ 0.2 -1.1]


Calculemos el producto $y = Ax$ :

In [0]:
y = A.dot(x)
print(y)

[-2.18 -4.53]


Calculemos la multiplicación $C = AB$, donde $A$, $B$, and $C$ son matrices:

In [0]:
B = np.array([[1.3, 0], [0, 2.0]])

C = A.dot(B)
print(C)

[[4.42 5.2 ]
 [2.73 9.  ]]


También podemos utilizar el operador @ (nuevo a partir python 3.5)

In [0]:

A = np.array([[1,2,3],
              [4,5,6]])
B = np.array([[9,8],
              [7,6],
              [5,4]])
print(np.dot(A,B))
print(A @ B)

[[ 38  32]
 [101  86]]
[[ 38  32]
 [101  86]]


La inversa de una matriz ($A^{-1}$) y su determinante  ($\det(A)$) se pueden obtener su utilizamos el módulo de NumPy s `linalg`:

In [0]:
Ainv = np.linalg.inv(A)
print("Inversa de A:\n {}".format(Ainv))

Adet = np.linalg.det(A)
print("Determinante de A: {}".format(Adet))

Inversa de A:
 [[ 0.45731707 -0.26422764]
 [-0.21341463  0.34552846]]
Determinante de A: 9.839999999999998



Una matriz Identidad  $I$. se puede crear utilizando

In [0]:
I = np.eye(4)
print(I)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## Resolución de un sistea de ecuaciones lineales
Mediante el uso de matrices podemos resolver ecuaciones lineales. For ejemplo, consideremos el sistema de ecuaciones:

\begin{equation}2x + 4y = 18\end{equation}
\begin{equation}6x + 2y = 34\end{equation}

Escrito en forma de matrices sería:

\begin{equation}\begin{bmatrix}2 & 4\\6 & 2\end{bmatrix} \cdot \begin{bmatrix}x\\y\end{bmatrix}=\begin{bmatrix}18\\34\end{bmatrix}\end{equation}

Notemos que las variables (***x*** and ***y***) se escriben como una columna de matriz (vector), que se multiplica por una matriz de coeficientes y se obtiene como resultado una matriz con los valores de las incógnitas. Si calculamos el producto punto en el lado izquierdo podemos ver claramente que representa el sistema de ecuaciones original:

\begin{equation}\begin{bmatrix}2x + 4y\\6x + 2y\end{bmatrix} =\begin{bmatrix}18\\34\end{bmatrix}\end{equation}

Demos nombre a nuestras matrices:

\begin{equation}A=\begin{bmatrix}2 & 4\\6 & 2\end{bmatrix}\;\;\;\;X=\begin{bmatrix}x\\y\end{bmatrix}\;\;\;\;B=\begin{bmatrix}18\\34\end{bmatrix}\end{equation}

Sabemos que ***A • X = B***, que aritméticamente representa ***X = B ÷ A***. Como la división de una matriz implica la multiplicación por su inversa, podemos encontrar los valores de nuestras variables (*X*) como: ***X = A<sup>-1</sup> • B***

Primero necesitamos calcular la inversa de A:

\begin{equation}\begin{bmatrix}2 & 4\\6 & 2\end{bmatrix}^{-1} = \frac{1}{(2\times2)-(4\times6)}  \begin{bmatrix}2 & -4\\-6 & 2\end{bmatrix}\end{equation}

\begin{equation}= \frac{1}{-20}  \begin{bmatrix}2 & -4\\-6 & 2\end{bmatrix}\end{equation}

\begin{equation}=\begin{bmatrix}-0.1 & 0.2\\0.3 & -0.1\end{bmatrix}\end{equation}

Ahora la multiplicamos por B:

\begin{equation}X = \begin{bmatrix}-0.1 & 0.2\\0.3 & -0.1\end{bmatrix} \cdot \begin{bmatrix}18\\34\end{bmatrix}\end{equation}

\begin{equation}X = \begin{bmatrix}(-0.1 \times 18)+(0.2 \times 34)\\(0.3\times18)+(-0.1\times34)\end{bmatrix}\end{equation}

\begin{equation}X = \begin{bmatrix}5\\2\end{bmatrix}\end{equation}

La matriz resultante (*X*) contiene los valores de  *x* and *y* variables, que lo podemos comprobar mediante las ecuaciones originales:

\begin{equation}(2\times5) + (4\times2) = 18\end{equation}
\begin{equation}(6\times5) + (2\times2) = 34\end{equation}

Que se convierte simplemente en:

\begin{equation}10 + 8 = 18\end{equation}
\begin{equation}30 + 4 = 34\end{equation}


Utilizando NUmpy esto es tan simple como:

In [0]:
A = np.array([[2,4],
              [6,2]])

B = np.array([[18],
              [34]])

X = np.dot(np.linalg.inv(A), B)
print(X)

[[5.]
 [2.]]


O bien

In [0]:

A = np.array([[2,4],
              [6,2]])

B = np.array([[18],
              [34]])

X = np.linalg.inv(A) @ B

print(X)

[[5.]
 [2.]]


O también utilizando el método **linalg.solve**

In [0]:
X = np.linalg.solve(A, B)
print(X)

[[5.]
 [2.]]



<p>Para más información, ver <a href="#ref">Numpy Quickstart tutorial</a></p>
