<a href="https://colab.research.google.com/github/gachet/000mis-colabs/blob/master/PREPARACION_SEGUNDO_PARCIAL_2026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Ejercicio Regresión Lineal Multivariable



#### Librerías

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d.axes3d import Axes3D
%matplotlib inline

#### Datos
El siguiente conjunto de datos contiene la tensión arterial sistólica (mmHg) (variable dependiente a predecir), la edad (años) y el peso (libras, 1 libra = 0.39 Kg) (mmHg) (variables independientes o predictoras)


In [ ]:
# X1 = systolic blood pressure; X2 = age in years, X3 = weight in pounds
blood_pressure_data = np.array([
    [132, 52, 173],
    [143, 59, 184],
    [153, 67, 194],
    [162, 73, 211],
    [154, 64, 196],
    [168, 74, 220],
    [137, 54, 188],
    [149, 61, 188],
    [159, 65, 207],
    [128, 46, 167],
    [166, 72, 217]
])


X: 

[[  1.  52. 173.]
 [  1.  59. 184.]
 [  1.  67. 194.]
 [  1.  73. 211.]
 [  1.  64. 196.]
 [  1.  74. 220.]
 [  1.  54. 188.]
 [  1.  61. 188.]
 [  1.  65. 207.]
 [  1.  46. 167.]
 [  1.  72. 217.]]


Suponiendo que tenemos una hipótesis de la forma  

$h_{\theta}(x)=\theta^{T} x=\theta_0+\theta_1x_1+\theta_2x_2$  
No es necesario normalizar los datos.  
Encontrar el vector $\theta$ utilizando :  
1.- Ecuaciones normales  
2.- La librería SckitLearn  
3.- En ambos casos calcular el error cuadrático medio dado por   
$\frac{1}{m} \sum_{i=1}^m(h_\theta(x^{(i)})-y^{(i)})^2$   
4.- Encontrar el vector $\theta$ utilizando el algoritmo del gradiente descendente con los siguientes parámetros:  

$max \ iteraciones = 100000\\
\alpha = 0.00001\\
\epsilon = 10e-6$
  
5.- Cual es el mínimo coste $J(\theta)$ obtenido con este método y con los dos primeros?  el algoritmo del gradiente converge ?  
6.- Comentarios y conclusiones


In [ ]:
Respuesta
coefficients:

[[30.99410295]
 [ 0.86141469]
 [ 0.3348592 ]]


##Ejercicio 2.- Para el conjunto de datos IRIS
from sklearn import datasets  
iris = datasets.load_iris()

Sin normalizar los datos

1.- Encontrar por regresión logistica mediante gradiente descendente
los valores del vector $\theta$ con los parámetros  
num_iter = 250000  
alpha = 0.1  
Utilizar un valor razonable de epsilon,   
Debería dar $\theta$ , por cada clase (5 parámetros)

theta:  [ 0.7794209   1.26223593  4.30162453 -6.8107031  -3.27548898]  
theta:  [ 7.37848655 -0.24535671 -2.79656809  1.31364331 -2.77834391]  
theta: [-22.82548815  -3.08449933  -5.31424996   7.24302427  12.90026622]

2.- Obtener los valores utilizando la regresión logística con Sckitlearn y comparar,

3,. Realizar una predicción para el conjunto de test Test  [6.4 2.8 5.6 2.2]  y comprobar por ambos métodos que se corresponde con la clase virginica.

4.- Con SkitLearn, obtener las métricas del modelo y la matria de confusión.