<a href="https://colab.research.google.com/github/gachet/000mis-colabs/blob/master/raices_polinomios_(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

## algoritmo

In [0]:
def roots(*coeffs):
    matrix = np.eye(len(coeffs) - 1, k=-1)
    matrix[:,-1] = np.array(coeffs[-1:0:-1]) / -coeffs[0] ## conmpanion matrix
    print(matrix)
    return np.linalg.eigvals(matrix)

In [0]:
#x^2-3x+2
roots(1, -3,2)

[[ 0. -2.]
 [ 1.  3.]]


array([1., 2.])

In [0]:
#x^2-10x+25
roots(1, -10,25)

[[  0. -25.]
 [  1.  10.]]


array([5., 5.])

In [0]:
# 10x - 1 = 0
roots(10, -1)

[[0.1]]


array([0.1])

In [0]:
# x^2 - 2x + 1 = 0
roots(1, -2, 1)

array([1., 1.])

In [0]:
# 2x^2 - 18 = 0
roots(2, 0, 18)

[[ 0. -9.]
 [ 1. -0.]]


array([ 0.+3.j, -0.-3.j])

In [0]:
# 1x^5 + x^4 + x^3 + x^2 + x + 1 = 0
roots(1, 1, 1, 1, 1, 1)

[[ 0.  0.  0.  0. -1.]
 [ 1.  0.  0.  0. -1.]
 [ 0.  1.  0.  0. -1.]
 [ 0.  0.  1.  0. -1.]
 [ 0.  0.  0.  1. -1.]]


array([ 0.5+0.8660254j,  0.5-0.8660254j, -1. +0.j       , -0.5+0.8660254j,
       -0.5-0.8660254j])

In [0]:
# 1x^5 + x^4 + x^3 + x^2 + x + 1 = 0
roots(1,-17,72.5)

array([8.5+0.5j, 8.5-0.5j])

In [0]:
# 1x^5 + x^4 + x^3 + x^2 + x + 1 = 0
roots(1,-3,0, 1)

array([-0.53208889,  0.65270364,  2.87938524])

In [0]:
##P4(x) = 3x4 − 10x3 − 48x2 − 2x + 12
roots(3,-10,-48, -2,12)

[[ 0.          0.          0.         -4.        ]
 [ 1.          0.          0.          0.66666667]
 [ 0.          1.          0.         16.        ]
 [ 0.          0.          1.          3.33333333]]


array([ 0.46163632, -0.56293642, -2.56536657,  6.        ])

In [0]:
##P3(x) = x3 − 4.0x2 − 4.48x + 26.1
roots(1,-4,-4.48, 26.1)

array([-2.39962495+0.j        ,  3.19981248+0.79868632j,
        3.19981248-0.79868632j])

In [0]:
## x4 − 5x3 − 9x2 + 155x − 250 = 0.
roots(1,-5,-9,155,-250)

array([-5.+0.j,  2.+0.j,  4.+3.j,  4.-3.j])

In [0]:
##3x3 + 7x2 􀀀 36x + 20
roots(3,7,-36,20)

array([ 2.        ,  0.66666667, -5.        ])

In [0]:
## w4 + 24w3 + 4500w2 + 18 E 103w + 2:25 E 6 = 0
roots(1,24,4500,18.0e3,2.25e6)

array([ -0.62301963+24.03024141j,  -0.62301963-24.03024141j,
       -11.37698037+61.35447281j, -11.37698037-61.35447281j])